# Generated by Django 5.0.3 on 2024-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_remove_todolist_created_remove_todolist_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
