# Используем базовый образ Python
FROM python:3.11

# Установка переменных среды
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Установка зависимостей
COPY ./todo_api/requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Копирование проекта в контейнер
COPY . /app
WORKDIR /app

# Запуск сервера Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
